import os
os.system("afplay ElevenLabsMandarinSample.mp3")  # MacOS Chinese language MP3 generated by ElevenLabs
# os.system("afplay ElectronicMusic_NoLyrics_Kalimba.mp3")  # MacOS electronic music with no lyrics

# or
# os.system("start output.mp3")  # Windows
